name: airport_paths
description: "Airport Paths - головоломка про прокладку безопасных маршрутов самолётов в аэропорту."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Игровой движок
  flame: ^1.18.0

  # Сохранение прогресса и настроек
  shared_preferences: ^2.2.3

  # Музыка и звуковые эффекты
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/audio/sfx/
    - assets/audio/music/
    - assets/images/

  # Когда добавишь свой шрифт - раскомментируй
  # fonts:
  #   - family: AirportDisplay
  #     fonts:
  #       - asset: assets/fonts/AirportDisplay-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/AirportDisplay-Black.ttf
  #         weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"